version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "elemental-failover-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d9siwzyemoyk"
s3_prefix = "elemental-failover-lambda"
region = "ap-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

