AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello_world

  Sample SAM Template for hello_world

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  S3EventLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: s3event.lambda_handler
      Runtime: python3.7
      Policies:
        - AmazonS3FullAccess
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: primary/
                  - Name: suffix
                    Value: .m3u8  
  
  SrcBucket:
    Type: AWS::S3::Bucket

Outputs:
  S3EventLambdaFunction:
    Description: "S3EventLambdaFunction ARN"
    Value: !GetAtt S3EventLambdaFunction.Arn
